---
os: linux
dist: trusty
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible>=2.0.0 ansible-lint
  - ansible --version
script:
  - ansible-lint tasks/main.yml
  # Prepare tests
  - echo localhost > inventory

  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml

  # First run
  - ansible-playbook -i inventory test.yml --connection=local --sudo

  ## Tests:
  # Verify driver version
  - cat /proc/driver/nvidia/version

  # Test nvcc installed
  - command -v nvcc >/dev/null 2>&1

  # Second run Idempotence test
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
